# Generated by Django 4.2.14 on 2024-08-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_out_of_stock_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='image',
            field=models.ImageField(default='image', upload_to='category_product/'),
            preserve_default=False,
        ),
    ]
